SCR_MissionHeader {
 World "{B744F5EE789F2870}worlds/Sarge/CO_Airmobile/CO_Airmobile.ent"
 m_sName "CO (40-64) Airmobile"
 m_sAuthor "Sarge"
 m_sDescription "US conducts air assault"
 m_sIcon "{27937F35E0F3C909}UI/Textures/Notifications/Notification_GameMaster_Voted.edds"
 m_sLoadingScreen "{F3FD9639CC14A643}UI/Textures/Map/testmap.edds"
 m_sPreviewImage "{F3FD9639CC14A643}UI/Textures/Map/testmap.edds"
 m_iPlayerCount 65
 m_bIsSavingEnabled 1
 m_bMapMarkerEnableDeleteByAnyone 1
 m_iMapMarkerLimitPerPlayer 50
}